smps_pkgs64:
  - libstdc++*
  - libidn*
  - libXext*
  - libXrender*
  - libXtst*
  - ncurses-libs*
  - ncurses-devel*
  - libXau*
  - libxcb*
  - compat-db42*
  - compat-db43*
  - libX11*
  - expat*
  - freetype*
  - fontconfig*
  - libICE*
  - libuuid*
  - libSM*
  - compat-libstdc++-33*
  - compat-db*
  - libXi*
  - libXft*
  - libXt*
  - libXp*
  - compat-libtermcap*
  - ksh
  - rng-tools
  - xorg-x11-xauth
  - unzip
  - sudo
  - which
  - sed

smps_pkgs32:
  - libstdc++.i686
  - libidn.i686
  - libXext.i686
  - libXrender.i686
  - libXtst.i686
  - ncurses-libs.i686
  - ncurses-devel.i686
  - libXau.i686
  - libxcb.i686
  - compat-db42.i686
  - compat-db43.i686
  - libX11.i686
  - expat.i686
  - freetype.i686
  - fontconfig.i686
  - libICE.i686
  - libuuid.i686
  - libSM.i686
  - compat-libstdc++-33.i686
  - compat-libstdc++-296.i686
  - compat-db.i686
  - libXi.i686
  - libXft.i686
  - libXt.i686
  - libXp.i686
  - compat-libtermcap.i686

smps126_pkgs64:
  - libstdc++
  - libidn
  - libXext
  - libXrender
  - libXtst
  - ncurses-libs
  - ncurses-devel
  - libXau
  - libxcb
  - libX11
  - expat
  - freetype
  - fontconfig
  - libICE
  - libuuid
  - libSM
  - compat-libstdc++-33
  - compat-db
  - libXi
  - libXft
  - libXt
  - libXp
  - ksh
  - rng-tools
  - xorg-x11-xauth
  - unzip
  - sudo
  - which
  - sed
